[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
package = "netlify-plugin-cache-nextjs"
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@netlify/plugin-sitemap"
package = "@netlify/plugin-nextjs"

  [plugins.inputs]
  buildDir = "out"